# Site settings
title: Hi, I'm Viswa Bonam.
description: Viswa Bonam's professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Viswa Sai Ammiraju Bonam 
#user_title: 
user_job_title: Data Science | FinTech and Analytics
exclude: ['package.json', 'src' , 'node_modules']
